package service

import "github.com/dpb587/go-schemaorg"

var (
	// The geographic area where the service is provided.
	ServiceArea = schemaorg.NewProperty("serviceArea")

	// The tangible thing generated by the service, e.g. a passport, permit, etc.
	Produces = schemaorg.NewProperty("produces")

	// The service provider, service operator, or service performer; the goods
	// producer. Another party (a seller) may offer those services or goods on
	// behalf of the provider. A provider may also serve as the seller.
	Provider = schemaorg.NewProperty("provider")

	// The audience eligible for this service.
	ServiceAudience = schemaorg.NewProperty("serviceAudience")

	// The geographic area where a service or offered item is provided.
	AreaServed = schemaorg.NewProperty("areaServed")

	// An intended audience, i.e. a group for whom something was created.
	Audience = schemaorg.NewProperty("audience")

	// Indicates an OfferCatalog listing for this Organization, Person, or Service.
	HasOfferCatalog = schemaorg.NewProperty("hasOfferCatalog")

	// The hours during which this service or contact is available.
	HoursAvailable = schemaorg.NewProperty("hoursAvailable")

	// Indicates the mobility of a provided service (e.g. 'static', 'dynamic').
	ProviderMobility = schemaorg.NewProperty("providerMobility")

	// The overall rating, based on a collection of reviews or ratings, of the item.
	AggregateRating = schemaorg.NewProperty("aggregateRating")

	// An offer to provide this item&#x2014;for example, an offer to sell a product,
	// rent the DVD of a movie, perform a service, or give away tickets to an event.
	Offers = schemaorg.NewProperty("offers")

	// An award won by or for this item.
	Award = schemaorg.NewProperty("award")

	// A category for the item. Greater signs or slashes can be used to informally
	// indicate a category hierarchy.
	Category = schemaorg.NewProperty("category")

	// An entity that arranges for an exchange between a buyer and a seller.  In
	// most cases a broker never acquires or releases ownership of a product or
	// service involved in an exchange.  If it is not clear whether an entity is a
	// broker, seller, or buyer, the latter two terms are preferred.
	Broker = schemaorg.NewProperty("broker")

	// The tangible thing generated by the service, e.g. a passport, permit, etc.
	ServiceOutput = schemaorg.NewProperty("serviceOutput")

	// An associated logo.
	Logo = schemaorg.NewProperty("logo")

	// A pointer to another, functionally similar product (or multiple products).
	IsSimilarTo = schemaorg.NewProperty("isSimilarTo")

	// A pointer to another, somehow related product (or multiple products).
	IsRelatedTo = schemaorg.NewProperty("isRelatedTo")

	// A means of accessing the service (e.g. a phone bank, a web site, a location,
	// etc.).
	AvailableChannel = schemaorg.NewProperty("availableChannel")

	// A review of the item.
	Review = schemaorg.NewProperty("review")

	// The type of service being offered, e.g. veterans' benefits, emergency relief,
	// etc.
	ServiceType = schemaorg.NewProperty("serviceType")

	// The brand(s) associated with a product or service, or the brand(s) maintained
	// by an organization or business person.
	Brand = schemaorg.NewProperty("brand")
)
