package report

import "github.com/dpb587/go-schemaorg"

// // A Report generated by governmental or non-governmental organization.
var Type = schemaorg.NewDataType("http://schema.org", "Report")

func New() *schemaorg.Thing {
	return schemaorg.NewThing(Type)
}
